### ISSUE TITLE
Maybe think of some way to get components through base component type

### ISSUE THREAD

**Issue by volcoma** [arvidsson/entity#9]
struct PhysicsBodyComponent
{
    // some general data
};
struct RigidBodyComponent : public PhysicsBodyComponent
{
    // some specific data
};
struct SoftBodyComponent : public PhysicsBodyComponent
{
    // some specific data
};
auto e = world.CreateEntity();
e.AddComponent\<PhysicsBodyComponent\>();

// somewhere else maybe a system's requirements
RequireComponent\<PhysicsBodyComponent\>();
auto& component = e.GetComponent\<PhysicsBodyComponent\>();

**Comment by arvidsson** [comment]
Better to add two components, the general and the specific one, than to rely on inheritance. I don't think it makes sense to have a hierarchy with components as it should be just data.
